"""new_user_store

Revision ID: 002
Revises: 001
Create Date: 2024-04-07 03:44:12.911806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('store_name', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_image_store', sa.Column('store_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_image_store_user_id_fkey', 'user_image_store', type_='foreignkey')
    op.create_foreign_key(None, 'user_image_store', 'user_store', ['store_id'], ['id'])
    op.drop_column('user_image_store', 'store_name')
    op.drop_column('user_image_store', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_image_store', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_image_store', sa.Column('store_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_image_store', type_='foreignkey')
    op.create_foreign_key('user_image_store_user_id_fkey', 'user_image_store', 'user', ['user_id'], ['id'])
    op.drop_column('user_image_store', 'store_id')
    op.drop_table('user_store')
    # ### end Alembic commands ###
