name: traveel_image_upload
services:
  nuclio:
    container_name: nuclio
    image: quay.io/nuclio/dashboard:stable-amd64
    restart: always
    networks:
      - russpass
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      NUCLIO_CHECK_FUNCTION_CONTAINERS_HEALTHINESS: 'true'
      NUCLIO_DASHBOARD_DEFAULT_FUNCTION_MOUNT_MODE: 'volume'
    ports:
      - '8070:8070'
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "3"

  clip-function:
    image: clip-function:latest
    container_name: clip-function
    networks:
      - russpass
    volumes:
      - ./serverless/function.yaml:/etc/nuclio/config/processor/processor.yaml
    ports:
      - 8090:8080

  backend:
    environment:
      ENABLE_SERVERLESS: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"
